### ISSUE TITLE
is LINE update protocol? 

### ISSUE THREAD

**Issue by Chriskatz** [merkremont/LineVodka#16]
Traceback (most recent call last):
  File "vodkabot.py", line 14, in <module>
    profile, setting, tracer = client.getProfile(), client.getSettings(), LineTracer(client)
  File "C:\LineVodka\LineAlpha\LineApi\LineClient.py", line 18, in checkLogin
    return func(*args, **kwargs)
  File "C:\LineVodka\LineAlpha\LineApi\LineClient.py", line 91, in getProfile
    return self._client.getProfile()
  File "C:\LineVodka\LineAlpha\LineThrift\TalkService.py", line 3886, in getProfile
    return self.recv_getProfile()
  File "C:\LineVodka\LineAlpha\LineThrift\TalkService.py", line 3897, in recv_getProfile
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "C:\Python27\lib\site-packages\thrift\protocol\TCompactProtocol.py", line 310, in readMessageBegin
    proto_id = self.__readUByte()
  File "C:\Python27\lib\site-packages\thrift\protocol\TCompactProtocol.py", line 289, in __readUByte
    result, = unpack('!B', self.trans.readAll(1))
  File "C:\LineVodka\LineAlpha\LineApi\LineTransport.py", line 100, in readAll
    raise EOFError()
EOFError

**Comment by doodspav** [comment]
yes (sort of)

**Comment by Chriskatz** [comment]
How to fix this problem？

**Comment by acx-nvstar** [comment]
yes me too, got the same problem

**Comment by fpitlok** [comment]
haha

**Comment by fpitlok** [comment]
it easy you fix

1.poll.py  2.Talk.py  3.chanal.py

UA = "Line/7.14.0"
LA = "IOSIPAD\t7.14.0\tiPhone OS\t10.12.0"

**Comment by ghost** [comment]
@fpitlok  could you please elaborate more please? do I just add it to each file?

**Comment by fpitlok** [comment]
# Bot vodka please look in 📁LineAlpha>LineApi

**in 📁LineApi check**  
1.LineServer.py
2.LineTransport.py
    
**chang**  UserAgent and Appname

**Change to this** 
UserAgent   = 'Line/7.14.0'
AppName     = 'IOSIPAD\t7.14.0\tiPhone OS\t10.12.0'

it easy :grin:

**Comment by semarainc** [comment]
thanks before for your solution @fpitlok, but that wouldnt work right now :(

**Comment by fpitlok** [comment]
LINE he update, Now can't fine token because he use password 2 time 😂

**Comment by fpitlok** [comment]
I know the reason is because LINE brings the certificate encryption.

It's easy to fix
you can find a CHOME user-agent to use, because CHOME has a valid certificate.

But It does not use the correct solution, because the real problem is "SSL" encryption.

I can only say this.
good luck 😊

**Comment by Al-an** [comment]
Your LINK QR is: line://au/q/oZa2BjlPFG2m5p7cfYs1cPVJHYF8CTry
Traceback (most recent call last):
  File "20bot.py", line 19, in <module>
    cl.login(qr=True)
  File "/home/cabox/workspace/TeamNoobBot/LINETNB/LineApi.py", line 40, in login
    self.Poll = Poll(self.authToken)
  File "/home/cabox/workspace/TeamNoobBot/LINETNB/Api/Poll.py", line 35, in __init__
    self.rev = self.client.getLastOpRevision()
  File "/home/cabox/workspace/TeamNoobBot/LINETNB/Api/../lib/curve/LineService.py", line 9884, in getLastOpRevision
    return self.recv_getLastOpRevision()
  File "/home/cabox/workspace/TeamNoobBot/LINETNB/Api/../lib/curve/LineService.py", line 9907, in recv_getLastOpRevision
    raise result.e
curve.ttypes.TalkException: TalkException(parameterMap=None, reason='LOG_OUT', code=8)

help

**Comment by acx-nvstar** [comment]
@Al-an 
since December 2017 you can not login using QR code / link for your LINE BOT, because LINE has updated their Api's
But there's another way to login your LINE BOT with AuthToken
Good luck

**Comment by arichd** [comment]
/qpython/projects/LineVodka-master/main.py" && exit                      <
Traceback (most recent call last):
  File "/storage/sdcard0/qpython/projects/LineVodka-master/main.py", line 12, in <module>
    client._qrLogin("line://au/q/")
  File "/storage/sdcard0/qpython/projects/LineVodka-master/LineAlpha/LineApi/LineApi.py", line 99, in _qrLogin
    qr = self._client.getAuthQrcode(keepLoggedIn, systemName)
  File "/storage/sdcard0/qpython/projects/LineVodka-master/LineAlpha/LineThrift/TalkService.py", line 2855, in getAuthQrcode
    self.send_getAuthQrcode(keepLoggedIn, systemName)
  File "/storage/sdcard0/qpython/projects/LineVodka-master/LineAlpha/LineThrift/TalkService.py", line 2865, in send_getAuthQrcode
    self._oprot.trans.flush()
  File "/storage/sdcard0/qpython/projects/LineVodka-master/LineAlpha/LineApi/LineTransport.py", line 112, in _f
    result = f(*args, **kwargs)
  File "/storage/sdcard0/qpython/projects/LineVodka-master/LineAlpha/LineApi/LineTransport.py", line 152, in flush
    self.__http.endheaders()
  File "/data/data/org.qpython.qpy/files/lib/python27.zip/httplib.py", line 1053, in endheaders
  File "/data/data/org.qpython.qpy/files/lib/python27.zip/httplib.py", line 897, in _send_output
  File "/data/data/org.qpython.qpy/files/lib/python27.zip/httplib.py", line 859, in send
  File "/data/data/org.qpython.qpy/files/lib/python27.zip/httplib.py", line 1278, in connect
  File "/data/data/org.qpython.qpy/files/lib/python27.zip/ssl.py", line 353, in wrap_socket
  File "/data/data/org.qpython.qpy/files/lib/python27.zip/ssl.py", line 601, in __init__
  File "/data/data/org.qpython.qpy/files/lib/python27.zip/ssl.py", line 830, in do_handshake
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
1|u0_a137@wsvga:/ $

pliz help me
